# Generated by Django 5.0.2 on 2024-02-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoEmotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotions_and_timestamp", models.JSONField()),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emo.video"
                    ),
                ),
            ],
        ),
    ]
