# Generated by Django 5.0.2 on 2024-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emo", "0002_videoemotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoemotions",
            name="emotions_and_timestamp",
            field=models.JSONField(null=True),
        ),
    ]
