# Generated by Django 5.0.2 on 2024-02-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emo", "0003_alter_videoemotions_emotions_and_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="video",
            name="video_tags",
            field=models.TextField(default="Enter Tag"),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.TextField(default="Enter title"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
