# Generated by Django 5.0.2 on 2024-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emo", "0004_video_video_description_video_video_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="Emotisement/%y"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_tags",
            field=models.TextField(default="no tags provided"),
        ),
    ]
